name: Bellybrief
favicon: null
layout_spectrum: 0.1891981230583042
typography_spectrum: 0.22298626974225044
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefefe'
    - '#d9ceb7'
    - '#0d0f02'
    - '#6f6c5c'
    - '#3a3c2e'
  brandStrength: 0.32167237577959895
  lightness: 0.7810503442306072
  saturation: 0.1743773405905813
  rhythmicContrast: 0.9650308242999017
purpose: []
